import Head from "next/head";
import Contributors from "../components/Contributors";

import Navbar from "../components/Navbar";
import Top from "../components/Top";

export default function Home() {
  return (
    <>
      <Head>
        <title>Github Stats</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <div className="body">
          <Top />
          <Contributors />
        </div>
      </main>
    </>
  );
}
